all: server-encoder client-decoder

server-encoder: server-encoder.c server-encoder.h
	gcc -Wall -o server-encoder server-encoder.c

client-decoder: client-decoder.c client-decoder.h
	gcc -Wall -o client-decoder client-decoder.c
